# Generated by Django 4.1.2 on 2022-10-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply_job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='dob',
            new_name='date_of_birty',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='experience',
        ),
    ]
