# Generated by Django 4.1.2 on 2022-10-14 12:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('apply_job', '0004_jobapplication_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='date_applied',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US', unique=True),
        ),
    ]
