# Generated by Django 4.1.2 on 2022-10-17 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply_job', '0006_jobapplication_current_ctc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='gender',
            field=models.CharField(choices=[('S', 'Select'), ('M', 'Male'), ('F', 'Female')], default='Select', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='position_applying',
            field=models.ForeignKey(default='Select', on_delete=django.db.models.deletion.CASCADE, to='apply_job.position'),
        ),
    ]
