# Generated by Django 4.1.2 on 2022-10-19 06:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("apply_job", "0010_alter_jobapplication_current_ctc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="date_of_birth",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="email",
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="expected_ctc",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="experience",
            field=models.CharField(
                choices=[
                    ("0", "Select"),
                    ("1", "Fresher"),
                    ("2", "1-2 years"),
                    ("3", "3-5 years"),
                    ("4", "6-8 years"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="nationality",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region="US"
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="title",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
