# Generated by Django 4.1.2 on 2022-10-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_job", "0016_alter_jobapplication_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Fresher"),
                    ("2", "1-2 years"),
                    ("3", "3-5 years"),
                    ("4", "6-8 years"),
                    ("5", "8+ years"),
                ],
                max_length=20,
            ),
        ),
    ]
