# Generated by Django 4.1.2 on 2022-10-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_job", "0017_alter_jobapplication_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
