# Generated by Django 4.1.2 on 2022-10-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_job", "0018_alter_jobapplication_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="email",
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
