# Generated by Django 4.1.2 on 2022-10-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apply_job", "0019_alter_jobapplication_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="first_name",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="last_name",
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
